language: android

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - build-tools-27.0.3
  - platform-tools
  - extra-android-m2repository
  - extra-google-android-support
  - android-27
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager 'platforms;android-27'
  - yes | sdkmanager 'build-tools;27.0.3'

script:
  - ./gradlew lint
  - ./gradlew test
  - ./gradlew assembleDebug

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
